### ISSUE TITLE
Support for `--exit-code` (single Github check)

### ISSUE THREAD

**Issue by MiroslavCsonka** [HeRoMo/pronto-action#123]
Currently, with following configuration:

```yml
jobs:
  pronto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: HeRoMo/pronto-action@v1.19.0
        with:
          github_token: ${{ secrets.github_token }}
          formatters: github_status text
```

The action will create 2 checks:
![CleanShot 2021-06-28 at 18 19 55@2x](https://user-images.githubusercontent.com/1818208/123686410-ae17b900-d847-11eb-8540-76b8f28d6138.png)

* `lint / pronto (pull_request) Successful in 1m` runs pronto, always successful, and holds the result of Pronto
* `pronto/rubocop — Found 14 warnings.` has the status and doesn't contain any links to see the warnings

Is there a way to have just one check that would contain the status AND link to the result? Would adding support for `--exit-code` and dropping `github_status` formatter do the trick?

**Comment by MiroslavCsonka** [comment]
I've tried forking this repo and adding a support for this, but because it uses a custom docker image, I ended up replacing the Github action with:

```yml
  pronto:
     name: run pronto
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v1
       - uses: ruby/setup-ruby@v1
         with:
           bundler-cache: true
       - name: Run Pronto
         run: bundle exec pronto run -f text -c origin/${{ github.base_ref }} --exit-code
```
